# Generated by Django 6.0.8 on 2026-08-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_solution_indicator_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='risk_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True, verbose_name='Seuil de risque'),
        ),
    ]
