# Generated by Django 6.0.8 on 2026-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_indicator_risk_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur cible'),
        ),
    ]
