# Generated by Django 6.0.8 on 2026-08-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_indicator_target_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='departement',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
