# Generated by Django 6.0.8 on 2026-08-14 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_administrateur_departement_delete_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='mitigation_plan',
            field=models.TextField(blank=True, verbose_name='Plan de mitigation'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unité'),
        ),
    ]
