# Generated by Django 6.0.8 on 2026-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_indicator_created_at_indicator_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AddField(
            model_name='administrateur',
            name='job_title',
            field=models.CharField(blank=True, help_text='Intitulé du poste', max_length=100, null=True, verbose_name='Fonction/Poste'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Dernière adresse IP de connexion', null=True, verbose_name='Dernière adresse IP'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='last_login_location',
            field=models.CharField(blank=True, help_text='Dernière localisation approximative', max_length=100, null=True, verbose_name='Dernière localisation'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone professionnel', max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
